name: "CI"
on:
  pull_request:
  push:
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - compiler: ghc965
          - compiler: ghc982
          - compiler: ghc9101
    steps:
    - uses: actions/checkout@v3
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main

    - run: nix -L build ".#checks.x86_64-linux.$GHCVER"
      env:
        GHCVER: ${{ matrix.compiler }}
